on:
  push:
    branches:
      - main
      - master

name: rmarkdown-build

jobs:
  rmarkdown-build:
    runs-on: ubuntu-20.04
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rmarkdown", "knitr", "tidyverse", "tidymodels", "randomForest", "pkgdown"))
        shell: Rscript {0}
        
      - name: Install Python
        run: |
          Rscript -e "remotes::install_github('rstudio/reticulate')"
          Rscript -e "reticulate::install_miniconda()"
          sudo apt install -y python3-venv python3-pip python3-setuptools
          sudo -H pip3 install virtualenv
          
      - name: Render site
        run: |
          reticulate::py_config()
          packages = c("numpy", "pandas", "scikit-learn")
          reticulate::virtualenv_create("r-reticulate", packages = packages, 
            python = "/Users/runner/Library/r-miniconda/envs/r-reticulate/bin/python")
          reticulate::py_install(packages = packages, envname = "r-reticulate",
            method = "virtualenv")
          reticulate::use_virtualenv("r-reticulate")
          reticulate::virtualenv_list()
          reticulate::py_module_available("numpy")
          reticulate::py_module_available("pandas")
          reticulate::py_module_available("scikit-learn")
          rmarkdown::render_site(".")
        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'pkgdown::deploy_to_branch(branch = "gh-pages", new_process = FALSE)'
